# Generated by Django 5.1.4 on 2024-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
